language: go
sudo: false
matrix:
  include:
    - go: 1.x
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
      arch: amd64
    - name: "arch: s390x"
      go: 1.13.x
      arch: s390x
    - name: "arch: arm64"
      go: 1.13.x
      arch: arm64
    - name: "arch: ppc64le"
      go: 1.13.x
      arch: ppc64le
    - go: tip
    - name: "Bazel Check"
      go: 1.x
      script: ./travisBazel.sh
      before_install:
        - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        - sudo apt-get update && sudo apt-get install bazel
    - name: "Make Check go 1.x"
      go: 1.x
      before_install:
        - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        - sudo apt-get update && sudo apt-get install bazel make
      script: make all

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/fatih/color
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/sergi/go-diff/diffmatchpatch

script: ./travisBuild.sh
